nguage: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      script: python test_linux.py
    - python: 3.7
      dist: windows
      sudo: true
      script: python test_win.py
